Pull Request-Bug 196
Azure/fedramp-iaas-webapp pull request #7
Opened 2017-11-20 13:39 UTC by gupta-yash

Resolved Bug 196- Do not store Azure credentials in Key Vault

As suggested, the Azure Credentials have been moved out from the Key Vault and now are being passed as normal parameters to the template.

2017-11-20 21:31 UTC, davoodharun requested changes
Can we remove the commented lines?

2017-11-21 05:42 UTC, gupta-yash commented
Yes, the commented lines in Orchestration_InitialSetup.ps1 can be removed.

2017-11-21 11:23 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/Azure/fedramp-iaas-webapp?pullRequest=7) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/Azure/fedramp-iaas-webapp?pullRequest=7) before we can accept your contribution.<br/><br/>:x: gupta-yash [sign now](https://cla.opensource.microsoft.com/Azure/fedramp-iaas-webapp?pullRequest=7)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/Azure/fedramp-iaas-webapp?pullRequest=7) it.</sub>

2017-11-27 17:36 UTC, davoodharun approved these changes

2017-11-28 12:21 UTC, merged